### ISSUE TITLE
Expected identifier, string or number

### ISSUE THREAD

**Issue by SilentT-FR** [perliedman/leaflet-control-geocoder#102]
IE 8 "the Monster ;)" detect lines 7 : 

Expected identifier, string or number
	class: L.Control.extend({

class need to be in double quote but other problems apear in others lines: 404 ect

**Comment by perliedman** [comment]
Ok, thanks for noticing and reporting.

I don't currently use this in any project that requires IE8, so if you require this, contributing a fix would be super!

I'm currently developing this in my free time, and since making IE8 fixes isn't my idea of a good time, this will not be a priority for me. Having said that - anyone contributing a fix would be really great.

**Comment by SilentT-FR** [comment]
a good how to http://mikemclin.net/fixing-error-script1028-expected-identifier-string-or-number/

**Comment by SilentT-FR** [comment]
https://github.com/perliedman/leaflet-control-geocoder/commit/b61b92788ecaaec52cc88634a9073a034ca33b37 

https://github.com/spicyj/es3ify/blob/master/index.js#L68
https://github.com/spicyj/es3ify/blob/master/index.js#L21
