### ISSUE TITLE
Regression showResultIcons

### ISSUE THREAD

**Issue by SilentT-FR** [perliedman/leaflet-control-geocoder#103]
showResultIcons default false but the icons appears 
when i force the option same problem

**Comment by perliedman** [comment]
Could you post the code you're using?

At least on the demo page, this works as expected: there are no icons: http://www.liedman.net/leaflet-control-geocoder/

**Comment by SilentT-FR** [comment]
http://jsfiddle.net/ktap3nnL/2/ i use 1.3.0

**Comment by perliedman** [comment]
Hm, tried this, and I don't get any icons. However, I don't get any icons if I set `showResultIcons` to `true` either.

Is the issue really that the icons _don't_ appear?

This is what it looks like when I use your fiddle:
![image](https://cloud.githubusercontent.com/assets/1246614/10992164/a83b5db8-8463-11e5-91d2-ca3054cce812.png)

**Comment by SilentT-FR** [comment]
Its normal i the icon dosent apair is not the problem : 
![sans titre](https://cloud.githubusercontent.com/assets/4253130/11014840/cbe09b9a-8547-11e5-8dc7-5d063d7b35a1.jpg)

**Comment by ram-one** [comment]
```showResultIcons``` option is used to show small icons beside results items.
If you want to remove the marker, you need to redefine ```markGeocode```function
```javascript

var geocoder = L.Control.Geocoder.nominatim();
geocoder.markGeocode = function (result) {
  this._map.fitBounds(result.bbox);
  return this;
};
```

Anyway, there is a bug with results icon, because they are not shown even if the option is set to true.

I guess this is because we set inner content of the link after the icon. So that icon is erased by the content 
https://github.com/perliedman/leaflet-control-geocoder/blob/master/src/control.js#L172

**Comment by SilentT-FR** [comment]
sorry for the mistake
