### ISSUE TITLE
Help with geocoder

### ISSUE THREAD

**Issue by dpineiden** [perliedman/leaflet-control-geocoder#116]
Hello
I'm using now your plugin to leaflet, i need to geocode an address, but i don't understand yet how to work with your geocoder method.

how to call geocoder?
what it's context inside geocoder function?

Thanks!

**Comment by perliedman** [comment]
Leaflet Control Geocoder is primarily a user interface control for geocoding in Leaflet, the map client.

However, you can also use the geocoding classes directly, like `L.Control.Geocoder.Nominatim`, if you want. The `geocode` method is asynchronous, so you have to pass it a callback that will be called when the result is done. The `context` parameter can be used to bind your callback to a specific object (so that `this` is assigned a value you choose), but you can omit it if you don't need it.

**Comment by dpineiden** [comment]
Thanks!  :)

**Comment by neogeomat** [comment]
Hi, 

Is there an example on how `context` is to be used? I am encountering an asynchronous programming issue, where the loop is not waiting for the geocode API to return a result before moving on to the next iteration. As a result, the returned result is being passed to the next iteration of the loop.
