### ISSUE TITLE
can geocoder use overpass api

### ISSUE THREAD

**Issue by RobyRemzy** [perliedman/leaflet-control-geocoder#122]
first thank you for your code, very useful.
i found this example of a search module using [overpass api](http://andreas-bruns.com/beispiele/example-overpass-api/)

is it possible to apply this kind of features to control-Geocoder? or is it too crazy or maybe overpass deserve it's own search module!
i'm new with Js, but if it's possible to extended geocoder to support overpass... could be awesome! and i will be more that happy to have a first look or help if i can.

**Comment by perliedman** [comment]
Sounds interesting, although it's not really what I would normally call a geocoder!

It's probably not that much work to do! You can look at one of the existing geocoders for an idea on how to implement it, they are very similar.

I would suggest putting it in a separate repository, since it's not really a normal geocoder, and likely only used by a few. I would be very happy to link to your extension, if you publish it.
