### ISSUE TITLE
Failed to load resource: net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by jcoupey** [perliedman/leaflet-control-geocoder#125]
First of all, thanks for sharing this geocoder!

When trying the `demo/index.html` from the latest release (v1.3.4), I'm not getting any marker and the callback function in `geocoder.reverse` is actually never called.

Investigating a little bit, I found out that everything is fine up to the `jsonp` call: the `script` tag for the nominatim request is added all right but the request fails because it points to a local resource. I get no error in Firefox (44.0+build3-0ubuntu0.15.04.1) but chromium does raise:

```
GET file://nominatim.openstreetmap.org/reverse?[...] net::ERR_FILE_NOT_FOUND
```

Don't know if this is related to any of my settings, but I tough it was worth reporting. Everything works as expected if I switch `serviceUrl` to `http://nominatim.openstreetmap.org/`in the `L.Control.Geocoder.Nominatim` code.

**Comment by perliedman** [comment]
This is because the geocoder by default uses a protocol relative URL, so if you run it from `file://` it will not work. You either have to specifically set `serviceUrl`, or load the demo page through http (or https).

I should probably change this to just always use https, since this is a quite common question... :smile:

**Comment by jcoupey** [comment]
Ok, thanks for the explanation and sorry for the noise. If you don't want to switch to https, maybe a comment where the client code lies in `demo/index.html` would spare you a few questions... ;-)
