### ISSUE TITLE
Not possible to write in the search box due to customized Bootstrap CSS

### ISSUE THREAD

**Issue by tbrcrl** [perliedman/leaflet-control-geocoder#128]
Hi, first of all thanks for this very useful plugin.
I am using it in a page built with Bootstrap framework and I found that it is not possible to write in the search box when I use a customized version of the bootstrap.css file.
Practically, when hovering on the search box, the cursor correctly assumes the property "text" but when clicking on the search box it is not possible "to place" the cursor inside the box in order to write, hence it is not possible to perform searches.
In the attached picture there is a side-by-side comparison between the solution that works, that makes use of the original bootstrap.css file, and the not working solution, that makes use of a customized bootstrap file (created according to the Bootstrap rules http://getbootstrap.com/customize/).
The application files used in the two cases are identical, the only difference being the bootstrap.css file to which they point.
Any idea or suggestion to solve the issue?

Many thanks in advance
[file-comparison.pdf](https://github.com/perliedman/leaflet-control-geocoder/files/242322/file-comparison.pdf)

**Comment by perliedman** [comment]
Hi there and thanks for using the geocoder!

It looks pretty apparent that this is some weird interaction caused by Bootstrap's CSS. It's really hard to say anything about why without having a running example, you could try making one or JSFiddle or so. I would be especially suspicious about any hover styles that Bootstrap might add.

Having said that, my time to debug issues caused by other libraries, like this one, is very close to none. If you can find a non-intrusive workaround, I would happily include it in the project!

**Comment by tbrcrl** [comment]
Hi, solved more easily than expected. The problem was caused by the color of the text used in the search box that is inherited from the body. As I customized Bootstrap with a body text white, the text (and also the cursor) in the search box was simply not visible. Then I just added a text color black to the geocoder CSS
.leaflet-control-geocoder-form {
    color: #000;
}
and everything works fine.
Thank you again for the geocoder!
