### ISSUE TITLE
1.5.4 from bower no dist folder

### ISSUE THREAD

**Issue by ThiagoMVF** [perliedman/leaflet-control-geocoder#155]
Bower downloaded 1.5.4 without the dist folder, which broke my CI. Fixing my project's used version to 1.5.3 for now.

**Comment by perliedman** [comment]
Hm, that's weird, the `dist` folder and its files is in the 1.5.4 tag: https://github.com/perliedman/leaflet-control-geocoder/tree/v1.5.4/dist

**Comment by bagage** [comment]
I tried on my own by manually triggering `build.sh`, `publish.sh` and `postbuild.sh`, then when bower fetchs it the `dist` folder **is** present.
It might be a problem either only when using `npm publish` or somewhat related to your enviroment system @perliedman?

**Comment by perliedman** [comment]
@bagage yes, the scripts you mention created the `dist` directory, so that is expected.

The strange thing is if bower for some reason does not fetch the `dist` folder, although it's clearly in the 1.5.4 tag (see above). I don't know why that is, since I don't use Bower.

Help to debug this welcome, but be advised that I will _not_ include the built files in the  `dist` folder except for release tags; this is BTW how Leaflet also handles Bower support.

**Comment by bagage** [comment]
@perliedman OK, so here's the thing: the `tar.gz` hosted on Github is wrong. If you do the following:

```
wget https://github.com/perliedman/leaflet-control-geocoder/archive/1.5.4.tar.gz 
tar xvf 1.5.4.tar.gz
```

You'll see that `dist` folder is NOT present. So…

1. Either you pushed the 1.5.4 tag a first time, then forced it again after having added `dist` folder? Maybe in that case GitHub won't regenerate the tag `tar.gz`.
2. Something else...

Anyway, I don't know how to make Github regenerate the tar.gz but this is the issue here.

**Comment by tsamaya** [comment]
the `.gitignore` file is excluding the `dist` folder

**Comment by drspangle** [comment]
This issue is still outstanding. It seems to have been fixed here:
https://github.com/Artyop/leaflet-control-geocoder.git#5e251844f778b9680a11a88278a81785d33cbdcc

**Comment by drspangle** [comment]
Would be really great if you could accept that dude's pull request (or implement their changes) so that we can use Bower to add this control as a dependency.

**Comment by perliedman** [comment]
@drspangle there's no pull request, as far as I know.

I would be happy to merge a fix for Bower users as long as the `dist` folder is still kept out of the repo with the exception of release tags, and the change doesn't involve other special magic for Bower, since I _will_ screw that up in the future, since I don't use Bower myself.

**Comment by drspangle** [comment]
Ah, I see. It seems that the problem is you've added the dist/ folder to
the gitignore for the release-tagged branch as well as the development
branches, which is the reason why Bower users are having trouble. All
you need to do is create a separate branch for releases with a gitignore
file that does not specify the dist/ folder should be ignored. You can
version tag these however you like. Then you can carry on doing what
you've been doing, and everyone should be happy. Bower doesn't rely on
the GitHub releases feature, rather, the only way it distinguishes what
versions to add as dependencies is the tags themselves.

It would be a good idea to update your bower.json file to reference
dist/Control.geocoder.js and .css under "main", as well, since that's
where they ought to be. Not sure that this is mandatory - I certainly
don't think this will break anything the way it is now.

**Comment by Rudloff** [comment]
Any news on this? I'm still stuck with 1.5.3 because of this issue.

**Comment by perliedman** [comment]
I have release version 1.5.5 just now, that appears to have fixed this issue.

**Comment by Rudloff** [comment]
I confirm it's fixed, thanks!
