### ISSUE TITLE
Geocoding form keeps flickering in Firefox

### ISSUE THREAD

**Issue by mdomnita** [perliedman/leaflet-control-geocoder#174]
This does not happen in Chrome, only in Firefox (v 56.0, Mac OSX here).
The mouseover/mouseout events keep opening and closing the form making it impossible to use. It started happening after I updated to the last version of the Geocoder control.

A video showing the behavior is here: https://youtu.be/wkJGVUgN96s

The behavior can be seen in the example app from this repository. My video also shows (in the second part) the behavior on a customized version in one of my pages (only icons changed from the css, no code modifications in the js.

I tried fiddling with the mouse events in the Control.Geocoder js file but didn't manage to find a quick solution.

**Comment by perliedman** [comment]
Hi, that is weird! I can't reproduce this on my system (Firefox 56.0 on Ubuntu Linux).

Looking at this, I found some weirdness on my system and added some fixes. Any chance you could try latest `master` and see if you still have the same problem?

**Comment by mdomnita** [comment]
Hello,
I just tried it in Windows 10, Firefox 56.2 (the example linked on the project github page) and it has the same behavior. I hover the mouse over the geocoder button, move it a little bit, the form disappears and then appears again. When I try to move the mouse in the input the form disappears and I cannot add any text.
I will try to get the latest version tomorrow at work and let you know.
Matei

**Comment by mdomnita** [comment]
Hello again,
I pulled the latest version and it works OK in firefox.
Thanks for the help.

**Comment by tperale** [comment]
I still had the same issue as @mdomnita here is my pull request which solved the issue

https://github.com/perliedman/leaflet-control-geocoder/pull/180

Also I was previously using `leaflet-control-geocoder` with _Chromium_ the bug didn't exist because in this part of the code

```javascript
				if (this.options.expand === 'click') {
					L.DomEvent.addListener(container, 'click', function(e) {
						if (e.button === 0 && e.detail !== 2) {
							this._toggle();
						}
					}, this);
				}
				else if (L.Browser.touch && this.options.expand === 'touch') {
					L.DomEvent.addListener(container, 'touchstart mousedown', function(e) {
						this._toggle();
						e.preventDefault(); // mobile: clicking focuses the icon, so UI expands and immediately collapses
						e.stopPropagation();
					}, this);
				}
				else {
					L.DomEvent.addListener(container, 'mouseover', this._expand, this);
					L.DomEvent.addListener(container, 'mouseout', this._collapse, this);
					this._map.on('movestart', this._collapse, this);
				}
```

_Chromium_ is considered as `L.Browser.touch && this.options.expand === 'touch'` so the popup don't expand on `mouseover`.

**Comment by derwu** [comment]
There are still issue in version 1.5.8 for Firefox (desktop). There are no possibility to search.

For Firefox 57.0.3 value of `L.Browser.touch` is still `undefined`. For chromium is `true`.

Solution is to set `expand: 'click'` in options, then condition in first `if` statement is truthy. In other way browser run last `else` statement which causes an issue (loop execution of functions: `this._expand` and `this._collapse` - because after `expand` search icon is hovered by search input and `collapse` function is called and so on).

Example:

```
let L_geocoderOptions = {
        expand: 'click'
    };

let L_geocoder = L.Control.geocoder(L_geocoderOptions)
```
