### ISSUE TITLE
Demo file won't run

### ISSUE THREAD

**Issue by tikky** [perliedman/leaflet-control-geocoder#232]
I am trying to run your demo/index.html

however file:
 "../dist/Control.Geocoder.css" 
is not in dist folder but in ../Control.Geocoder.css 

and "../dist/Control.Geocoder.js" **doesn't exist in the repository**.
Is now file called "Control.Geocoder.js" and no folder called "dist".

Could you please let me know how to run this demo.

**Comment by KristjanESPERANTO** [comment]
I'm also new here, but have found the dist folder and also the files.
How did you download the files? In the README  [1] is a link to the latest releases: https://github.com/perliedman/leaflet-control-geocoder#usage

**Comment by perliedman** [comment]
Hi!

It is correct that `dist` is not part of repository, and it is intentional. `dist` contains the built files, and are not distributed with the repository itself. This is a convention that you will find that almost all projects follow these days, committing build artifacts to the repository is an anti-pattern.

You need to build the project (`npm run build`) to create the `dist` folder and its contents.
