### ISSUE TITLE
Craft a 1.8.0 release?

### ISSUE THREAD

**Issue by simon04** [perliedman/leaflet-control-geocoder#246]
We've integrated a bunch of new features as well as bugfixes since 1.7.0, see https://github.com/perliedman/leaflet-control-geocoder/compare/v1.7.0...master. Should we craft a new release? Thank you!

**Comment by perliedman** [comment]
Yup! Probably a good idea, I seem to remember people bugging me about this, but haven't gotten around to doing it.

Is there anything more we need to consider than just running `npm publish`? Feel free to just do it, if you want (I think you have npm publishing permissions, right?) Otherwise, I'll do it Any Day Now™ :smile:

**Comment by simon04** [comment]
Done – 1.8.0 is out :rocket: 
I wasn't aware of the npm permissions…

**Comment by perliedman** [comment]
Nice work, thanks!

I might have added you but forgot to actually tell you...
