### ISSUE TITLE
Property 'Geocoder' does not exist on type 'typeof Control'.ts

### ISSUE THREAD

**Issue by SikFar** [perliedman/leaflet-control-geocoder#260]
Hi,

Im getting error message
`Property 'Geocoder' does not exist on type 'typeof Control'.ts(2339)
`
`Property 'geocoder' does not exist on type 'typeof Control'.`

I have installed trough with `npm i leaflet-control-geocoder` 
This the code where im getting the errors:

`    geocoder = L.Control.Geocoder.nominatim()
`
and
```
 L.Control.geocoder({
            geocoder: this.geocoder
          }).addTo(this.map);
```

Please help

**Comment by perliedman** [comment]
Hi, this looks like a TypeScript related error. I don't use TypeScript myself, so I don't know how to work around it, but it looks like it is complaining about how this plugin attaches itself to Lealfet's `L.Control` class.

Not really related to this plugin, so I'm going to close this, but feel free to add a comment about how to solve it if you find a solution.

**Comment by zaferad** [comment]
Hi @perliedman, this issue is related with type definitions missing in TypeScript projects using the library, e.g. in newer angular projects using leaflet in a setup like this (package.json):

`"@asymmetrik/ngx-leaflet": "^6.0.1",`
`"leaflet": "^1.5.7",`
`"leaflet-control-geocoder": "^1.8.2",`
`"leaflet.fullscreen": "^1.5.1",`
`"leaflet.markercluster": "^1.4.1",`

Then in order to be able to develop in Typescript, one needs type definitions for these packages (devDependencies in package.json):

`"@types/leaflet": "^1.5.12",`
`"@types/leaflet.markercluster": "^1.4.2",`
`"@types/leaflet.fullscreen": "^1.6.0",`

Since there are no definitions, there is an error. One would have to add these type definitions to this project and publish it as a package:
https://github.com/DefinitelyTyped/DefinitelyTyped

Then we could import it as `@types/leaflet-control-geocoder` and the error would not just be gone, we would have type safety whilst developing.

**Comment by simon04** [comment]
The Leaflet typings are maintained by DefinitelyTyped not Leaflet: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet/index.d.ts

See #279 for a (potential) migration to TypeScript.

**Comment by phileasthefogg** [comment]
Has this issue been resolved?  I saw that the typescript branch has now been pushed/closed but I'm still running into this error.  Any updates/workarounds available?

**Comment by bhagattamu** [comment]
> Has this issue been resolved? I saw that the typescript branch has now been pushed/closed but I'm still running into this error. Any updates/workarounds available?
```
import * as L from 'leaflet';
import Geocoder from 'leaflet-control-geocoder';

...
const GeocoderControl = new Geocoder();
GeocoderControl.addTo(this.map);
```

**Comment by simon04** [comment]
This should work: 

```typescript
import {Geocoder, geocoders} from 'leaflet-control-geocoder';
new Geocoder({
  geocoder: new geocoders.Nominatim(),
  position: 'topleft',
}).addTo(map);
```

**Comment by brandonporcel** [comment]
leaflet and google maps are totally different things?
Im trying to create Geocoder class from google maps but i have an ts error

`const { Geocoder } = await google.maps.importLibrary('geocoding');`
`Property 'Geocoder' does not exist on type 'CoreLibrary | MapsLibrary | PlacesLibrary | GeocodingLibrary | RoutesLibrary | MarkerLibrary | ... 5 more ... | VisualizationLibrary'.ts(2339)`
