### ISSUE TITLE
Make lib available through bower

### ISSUE THREAD

**Issue by erf** [perliedman/leaflet-control-geocoder#27]
Make lib available through bower

**Comment by JonasKa** [comment]
I would also apprentice to make it available through Bower.
 
Simply push a bower.json file with similar name, version values etc. as your package.json. 

Just beware to change the version property to a valid version number. Meaning eg. changing from "release-v1.0.0" to "1.0.0".

The main property should be:
"main": [
    "Control.Geocoder.css",
    "Control.Geocoder.js"
  ]
This enables automatic includes of the needed files.

After pushed the bower.json, register it with:
bower register leaflet-control-geocoder git://github.com/perliedman/leaflet-control-geocoder

The register task, I think, is a reason for you pushing it instead of someone else.

Thank you

**Comment by GuillaumeAmat** [comment]
Someone already register it in the bower registry, but the last version (1.0.0) is not available due to the « bad naming » of the git tag...
Like @JonasKa said, a bower.json file cold resolve this and it will be greatly usefull to the bower users :)

**Comment by perliedman** [comment]
Fixed by https://github.com/GuillaumeAmat/leaflet-control-geocoder/commit/3f625dfdd0d03975b42ebc4799051e4c4cec69c1 (I believe?)

**Comment by GuillaumeAmat** [comment]
Damned. It seems that the bower.json file is not enough... The version tags have to be in the x.x.x style.
Like all your old tags. Can you rename the last tag or at least create a new one?

**Comment by perliedman** [comment]
@GuillaumeAmat done: https://github.com/perliedman/leaflet-control-geocoder/tree/1.0.0

**Comment by GuillaumeAmat** [comment]
Aaaaand it works! ;) Thanks
