### ISSUE TITLE
nice plugin, but in IE 11 the search don't pen when clicking on the search icon.

### ISSUE THREAD

**Issue by nijs9** [perliedman/leaflet-control-geocoder#46]

**Comment by perliedman** [comment]
Hi,
have you verified with the latest version from git, or did you check the plugin demopage?

IE11 support should have been fixed in f2d480c959f10e0bb6c62205d402daf4da231011, but I haven't yet put that up on the demo site.

This means, if you're seeing this bug using the latest code, there's still a bug. If it's just on the demo site, there's a good chance this bug is already fixed.

**Comment by nijs9** [comment]
Hi Per

You are absolutely right; in the latest version it works in IE11.

Thanks for your reply and the good work!

Met vriendelijke groet
Sven Nijs
[cid:image001.png@01CEDEC1.972AEBF0]

2infinIT BVBA
Mortelbroekstraat 32
3271 Averbode
0472 86 67 54

Van: Per Liedman [mailto:notifications@github.com]
Verzonden: dinsdag 27 januari 2015 12:52
Aan: perliedman/leaflet-control-geocoder
CC: nijs9
Onderwerp: Re: [leaflet-control-geocoder] nice plugin, but in IE 11 the search don't pen when clicking on the search icon. (#46)


Hi,
have you verified with the latest version from git, or did you check the plugin demopage?

IE11 support should have been fixed in f2d480c<https://github.com/perliedman/leaflet-control-geocoder/commit/f2d480c959f10e0bb6c62205d402daf4da231011>, but I haven't yet put that up on the demo site.

This means, if you're seeing this bug using the latest code, there's still a bug. If it's just on the demo site, there's a good chance this bug is already fixed.

**Comment by JonasKa** [comment]
This issue only seems to be fixed on master branch. Please also fix it in release 'release-v..' tag or add component to Bower.

Thank you
