### ISSUE TITLE
Potential issue in readme

### ISSUE THREAD

**Issue by dtruel** [perliedman/leaflet-control-geocoder#55]
"I strongly believe that it is my — and your — duty to make the open source community, as well as the tech community at large, a community where everyone feel welcome and is accepted.  It means being friendly and inclusive, even when you disagree with people."

"If you think feminism, anti-racism or the LGBT movement is somehow wrong, disturbing or irrelevant, I ask you to go elsewhere to find software."

-This seems contradictory.  Here you say "...It means being friendly and inclusive, even when you disagree", and then you say that anyone who disagrees should go away.

Maybe you ought to rethink this. Maybe you should just post your opinion on it, but then also demonstrate that you too are inclusive, and accept people who believe differently from you too.  If you say "anyone who thinks being gay is wrong can't use my software", how are you any different?  It seems to me like you are violating the principle you just stated above.  FOSS is closely linked to freedom of speech and thought, and this doesn't seem like it goes well with the idea.

**Comment by perliedman** [comment]
Your example is flawed. Thinking it's wrong to be gay is an abusive opinion; you take the right to value someone based on their sexuality, which they did not choose; the same goes for the other categories mentioned. When expressing those views on the other hand, you chose to have that opinion, and forcing it on others. Being welcoming to such views and expressions effectively makes the community less welcoming to the groups they speak against. In short, the idea is to be welcoming to people who are welcoming; people who can't respect other for who they are, are not welcome.

I'm well aware of the history of freedom of speech and FOSS, and while I welcome free speech in the society at large, I think its role in the open source movement has often been to justify bad behaviour from a group ignorant of their own privilege, and it has made it unnecessarily hard to be part of open source if you're not young, white, male and heterosexual. While not directly linked to open source, the same mechanics are at work in the so called "gamergate" catastrophe, where threats, abuse and generally incredibly shitty behaviour is done under the pretense of "free speech".

I think it is my, and others, moral obligation to try, if just in a very small way, to stop this, instead of standing by the side pretending to be objective and say "hey, anything goes, because - free speech!". That is not the way forward.
