### ISSUE TITLE
Using own html control button instead of leaflet

### ISSUE THREAD

**Issue by collmomo** [perliedman/leaflet-control-geocoder#57]
How are supposed to do this with your plugin. I understand I could create a new nominatim geocode object and then call markgeocode, however Im not sure if its the best way. I really like this plugin, I just dont wanna put the control on the map.

**Comment by perliedman** [comment]
Instead of using `L.Control.Geocoder`, which is the user interface, you can use for example `L.Control.Geocoder.Nominatim` directly to make queries and get back the results. It has two methods, `geocode` and `reverse`, check out the IGeocoder interface for details on how they work: https://github.com/perliedman/leaflet-control-geocoder#igeocoder
